export const school = { name: 'FutureLab', year: '2026–27', updated: '24 September 2026' }
export const stages = [
  {
    id: 'early-years',
    name: 'Early years',
    range: 'Nursery – KG',
    ages: '3–5 years',
    headline: 'Small discoveries. Giant possibilities.',
    description:
      'A joyful beginning through stories, sensory play, movement and making. Every question is a wonderful place to start.',
    subjects: ['Language & stories', 'Number play', 'Creative expression', 'Our world'],
    image: 'early',
  },
  {
    id: 'primary',
    name: 'Primary',
    range: 'Classes I – V',
    ages: '6–10 years',
    headline: 'A strong foundation. An open mind.',
    description:
      'Build confident readers, thoughtful problem-solvers and curious collaborators through an integrated ICSE-oriented learning journey.',
    subjects: ['English & Hindi', 'Mathematics', 'Environmental science', 'Computational thinking'],
    image: 'classroom',
  },
  {
    id: 'middle',
    name: 'Middle school',
    range: 'Classes VI – VIII',
    ages: '11–13 years',
    headline: 'More questions. More ways to find out.',
    description:
      'Connect the sciences, humanities and arts with hands-on projects, independent research and purposeful technology.',
    subjects: ['Physics & Chemistry', 'Biology', 'History & Geography', 'Mathematics & languages'],
    image: 'hero',
  },
  {
    id: 'secondary',
    name: 'Secondary',
    range: 'Classes IX – X',
    ages: '14–16 years',
    headline: 'Deep understanding. Real-world ambition.',
    description:
      'An ICSE-oriented pathway that balances subject depth, thoughtful exam preparation and the freedom to explore what comes next.',
    subjects: ['Sciences', 'Commercial studies', 'Computer applications', 'Languages & humanities'],
    image: 'computer',
  },
]
export const interests = [
  'All interests',
  'Science & robotics',
  'Arts & expression',
  'Sport & wellbeing',
  'Language & literature',
]
export const projects = [
  {
    slug: 'little-ideas-big-impact',
    title: 'Little ideas. Big impact.',
    category: 'Science & robotics',
    image: 'project',
    label: 'THE INNOVATION LAB',
    class: 'Class VII',
    description: 'Turning a question about cleaner cities into a working renewable-energy model.',
    challenge: 'How can a neighbourhood make better use of clean energy?',
    process:
      'Teams mapped everyday energy use, explored simple circuits and tested ideas with recycled materials.',
    prototype:
      'A tabletop model connects a small solar panel to a lighting circuit. Students document what changes under different light conditions.',
    reflection:
      'The best prototype was not the first one. Recording failures helped the team build a more reliable circuit.',
  },
  {
    slug: 'colour-outside-the-lines',
    title: 'Colour outside the lines.',
    category: 'Arts & expression',
    image: 'art',
    label: 'THE CREATIVE STUDIO',
    class: 'Classes IV–VI',
    description: 'Finding a voice, one sketch, colour and conversation at a time.',
    challenge: 'How can a poster help someone see the world differently?',
    process:
      'Students collected visual references, sketched ideas and exchanged constructive feedback.',
    prototype: 'A collaborative poster series about caring for our shared environment.',
    reflection: 'A simple message can be powerful when image and words work together.',
  },
  {
    slug: 'stronger-together',
    title: 'Stronger, together.',
    category: 'Sport & wellbeing',
    image: 'sports',
    label: 'BEYOND THE CLASSROOM',
    class: 'Whole school',
    description: 'Building teamwork, resilience and a little friendly competition.',
    challenge: 'What does it mean to be a good teammate?',
    process: 'Students tried team challenges, rotated leadership and reflected after each session.',
    prototype: 'A student-created playbook of inclusive games.',
    reflection: 'Winning feels good. Helping everyone participate feels even better.',
  },
]
export const gallery = [
  {
    image: 'hero',
    title: 'A closer look at a bigger world',
    category: 'Learning',
    event: 'Reading hour',
    year: '2026',
    caption: 'A quiet moment of reading from the supplied school photo collection.',
  },
  {
    image: 'dance',
    title: 'Their stage. Their moment.',
    category: 'Arts & culture',
    event: 'Annual celebration',
    year: '2026',
    caption: 'Colour, expression and confidence on the annual-day stage.',
  },
  {
    image: 'sports',
    title: 'A little grit. A lot of joy.',
    category: 'Sports',
    event: 'Sports day',
    year: '2026',
    caption: 'Outdoor teamwork and friendly competition.',
  },
  {
    image: 'children',
    title: 'Learning is better together',
    category: 'Learning',
    event: 'Discovery day',
    year: '2026',
    caption: 'Collaborative learning through making and conversation.',
  },
  {
    image: 'art',
    title: 'Ideas in every colour',
    category: 'Arts & culture',
    event: 'Creative studio',
    year: '2025',
    caption: 'Students explore their creativity in a poster-making activity.',
  },
  {
    image: 'project',
    title: 'From “what if” to “we made it”',
    category: 'Innovation',
    event: 'Project showcase',
    year: '2026',
    caption: 'Students share their science models and explain their thinking.',
  },
  {
    image: 'yoga',
    title: 'Room to pause. Space to grow.',
    category: 'Sports',
    event: 'Wellbeing week',
    year: '2025',
    caption: 'A shared movement and mindfulness session.',
  },
  {
    image: 'festival',
    title: 'Many voices. One community.',
    category: 'Arts & culture',
    event: 'Annual celebration',
    year: '2026',
    caption: 'A school celebration brings music, dance and stories together.',
  },
  {
    image: 'computer',
    title: 'Tomorrow starts with a click',
    category: 'Innovation',
    event: 'Digital discovery',
    year: '2025',
    caption: 'Exploring digital tools in the computer laboratory.',
  },
  {
    image: 'riding',
    title: 'A new kind of confidence',
    category: 'Sports',
    event: 'Outdoor learning',
    year: '2026',
    caption: 'Learning through a supervised outdoor experience.',
  },
  {
    image: 'music',
    title: 'Find your own rhythm',
    category: 'Arts & culture',
    event: 'Annual celebration',
    year: '2026',
    caption: 'Young performers come together for a group performance.',
  },
  {
    image: 'classroom',
    title: 'The everyday extraordinary',
    category: 'Learning',
    event: 'Classroom stories',
    year: '2025',
    caption: 'A collaborative classroom moment from the supplied collection.',
  },
]
export const facilities = [
  {
    slug: 'discovery-lab',
    name: 'Discovery lab',
    tag: 'OBSERVE · EXPERIMENT · REPEAT',
    image: 'science',
    detail:
      'Dedicated spaces for physics, chemistry and biology turn textbook ideas into hands-on exploration. Guided demonstrations and safety briefings are part of every lab session.',
    access: 'Ground-floor entry in the illustrative campus plan.',
    x: 31,
    y: 32,
  },
  {
    slug: 'maker-space',
    name: 'Maker space',
    tag: 'IDEATE · BUILD · ITERATE',
    image: 'project',
    detail:
      'A collaborative studio for circuits, robotics and student prototypes. Work benches support small-group project work.',
    access: 'Accessible route shown on the illustrative campus plan.',
    x: 62,
    y: 25,
  },
  {
    slug: 'library',
    name: 'The reading room',
    tag: 'READ · WONDER · DISCOVER',
    image: 'library',
    detail:
      'A place for quiet reading, research and lively book conversations. Fiction, reference titles and project resources sit side by side.',
    access: 'Step-free entrance in the illustrative plan.',
    x: 25,
    y: 68,
  },
  {
    slug: 'creative-studio',
    name: 'Creative studio',
    tag: 'IMAGINE · EXPRESS · CONNECT',
    image: 'art',
    detail:
      'Art, storytelling and performance meet in a flexible creative learning space. Students develop their own voice through practice and feedback.',
    access: 'Lift access would require school verification.',
    x: 68,
    y: 65,
  },
  {
    slug: 'sports-ground',
    name: 'Sports & outdoors',
    tag: 'MOVE · PLAY · BELONG',
    image: 'sports',
    detail:
      'Open space for team sports, movement and outdoor discovery. A balanced week makes room for wellbeing and friendly competition.',
    access: 'Outdoor route; surface accessibility requires verification.',
    x: 49,
    y: 51,
  },
]
export const events = [
  {
    slug: 'discovery-day',
    title: 'Discovery Day: come curious',
    category: 'Open house',
    date: '2026-10-17',
    day: '17',
    month: 'OCT',
    time: '10:00–12:00 IST',
    image: 'children',
    detail:
      'Meet our educators, explore the labs and try a little hands-on learning. This fictional open-house event welcomes prospective families.',
  },
  {
    slug: 'innovation-fair',
    title: 'Small ideas, big possibilities',
    category: 'Student showcase',
    date: '2026-11-07',
    day: '07',
    month: 'NOV',
    time: '09:30–13:00 IST',
    image: 'project',
    detail:
      'Student teams share their projects, explain the process and reflect on what they would try next.',
  },
  {
    slug: 'community-festival',
    title: 'A celebration of belonging',
    category: 'Community',
    date: '2026-12-12',
    day: '12',
    month: 'DEC',
    time: '16:00–18:00 IST',
    image: 'dance',
    detail:
      'An evening of student performances, art and shared stories for the whole school community.',
  },
]
export const clubs = [
  {
    slug: 'robotics',
    title: 'The Tinker Club',
    interest: 'Science & robotics',
    image: 'project',
    description: 'Build circuits, code a little and ask bigger questions.',
    schedule: 'Tuesday · 15:00–16:00',
    eligibility: 'Classes IV–VIII',
    places: 6,
  },
  {
    slug: 'art',
    title: 'Studio Curious',
    interest: 'Arts & expression',
    image: 'art',
    description: 'A creative playground for bold ideas and small masterpieces.',
    schedule: 'Wednesday · 15:00–16:00',
    eligibility: 'Classes I–VIII',
    places: 8,
  },
  {
    slug: 'sports',
    title: 'The Outdoor Collective',
    interest: 'Sport & wellbeing',
    image: 'sports',
    description: 'Move, play and discover the power of a team.',
    schedule: 'Friday · 15:00–16:00',
    eligibility: 'Classes III–X',
    places: 0,
  },
  {
    slug: 'literature',
    title: 'Between the Lines',
    interest: 'Language & literature',
    image: 'library',
    description: 'For big readers, aspiring writers and wonderful storytellers.',
    schedule: 'Thursday · 15:00–16:00',
    eligibility: 'Classes III–X',
    places: 10,
  },
]
export const notices = [
  {
    slug: 'term-two-calendar',
    title: 'Your guide to Term II',
    category: 'Academic',
    class: 'All classes',
    date: '2026-09-24',
    detail:
      'Term II begins on 5 October 2026. Discovery Day is on 17 October, the Innovation Fair on 7 November, and the Community Festival on 12 December. Please review the calendar with your child.',
  },
  {
    slug: 'science-projects',
    title: 'Calling all curious minds',
    category: 'Activities',
    class: 'Classes VI–VIII',
    date: '2026-09-22',
    detail:
      'Submit your Innovation Fair project idea by 15 October 2026. Work in teams of up to four. Include your question, materials and proposed experiment. Your science educator will review each proposal.',
  },
  {
    slug: 'library-week',
    title: 'One book. A thousand possibilities.',
    category: 'Community',
    class: 'All classes',
    date: '2026-09-18',
    detail:
      'Reading Week runs from 5 to 9 October 2026. Bring a favourite book on Monday and join the Friday story circle. Borrowing hours are 08:30–15:30 on school days.',
  },
]
export const faculty = [
  {
    slug: 'ananya-rao',
    name: 'Ananya Rao',
    department: 'Sciences',
    initials: 'AR',
    qualification: 'M.Sc., B.Ed.',
    role: 'Science & inquiry lead',
    intro: 'Makes room for the big questions and the experiments that follow.',
  },
  {
    slug: 'kabir-mehta',
    name: 'Kabir Mehta',
    department: 'Technology',
    initials: 'KM',
    qualification: 'B.Tech., B.Ed.',
    role: 'Computing & maker educator',
    intro: 'Connects code, creativity and real-world problem solving.',
  },
  {
    slug: 'meera-sen',
    name: 'Meera Sen',
    department: 'Humanities',
    initials: 'MS',
    qualification: 'M.A., B.Ed.',
    role: 'Language & literature lead',
    intro: 'Helps every learner discover the power of their own voice.',
  },
  {
    slug: 'isha-kapoor',
    name: 'Isha Kapoor',
    department: 'Arts',
    initials: 'IK',
    qualification: 'M.F.A., B.Ed.',
    role: 'Creative arts educator',
    intro: 'Believes creative confidence grows through exploration and practice.',
  },
]
export const publicIndex = [
  ...stages.map((s) => ({
    title: s.name,
    type: 'Academics',
    text: s.description + ' ' + s.subjects.join(' '),
    path: '/academics/' + s.id,
  })),
  ...clubs.map((s) => ({
    title: s.title,
    type: 'Clubs',
    text: s.description + ' ' + s.interest,
    path: '/clubs/' + s.slug,
  })),
  ...facilities.map((s) => ({
    title: s.name,
    type: 'Campus',
    text: s.detail,
    path: '/campus/' + s.slug,
  })),
  ...notices.map((s) => ({
    title: s.title,
    type: 'Notices',
    text: s.detail,
    path: '/notices/' + s.slug,
  })),
  {
    title: 'Admissions & documents',
    type: 'Admissions',
    text: 'Apply, eligibility, birth certificate, report card, fee estimate, visit',
    path: '/admissions',
  },
  {
    title: 'Student life in full colour',
    type: 'Gallery',
    text: 'Photos sports arts culture science innovation events',
    path: '/gallery',
  },
  {
    title: 'Download centre',
    type: 'Resources',
    text: 'Prospectus class 6 book list calendar syllabus',
    path: '/downloads',
  },
]
